name: flutter_clean_starter

sdkPath: .fvm/flutter_sdk

packages:
  - packages/app
  - packages/common
  - packages/data/data_post
  - packages/data/data_profile
  - packages/domain/domain_post
  - packages/domain/domain_profile
  - packages/presentation/feature_common
  - packages/presentation/feature_dashboard
  - packages/presentation/feature_feed
  - packages/presentation/feature_bookmark
  - packages/presentation/feature_profile

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  generate:
    run: melos exec -c 1 --depends-on="build_runner" --flutter -- "fvm dart run build_runner build --delete-conflicting-outputs"
    description: run build_runner for all packages