name: flutter_clean_starter

sdkPath: .fvm/flutter_sdk

packages:
  - packages/app
  - packages/common

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  generate:
    run: melos exec -c 1 --depends-on="build_runner" --flutter -- "fvm dart run build_runner build --delete-conflicting-outputs"
    description: run build_runner for all packages