name: app
description: "Main app module."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  common:
    path: ../common

  get_it: ^8.0.0
  auto_route: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
