name: domain_post
description: "Domain module for anything post-related."

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  common:
    path: ../../common

  cupertino_icons: ^1.0.8
  get_it: ^8.0.0
  injectable: ^2.5.0
  mockito: ^5.4.2
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  test: ^1.25.8
